add content-type text/yaml as supported icontent-type to import
anymaniax/orval pull request #109
Opened 2021-01-15 09:12 UTC by wouterkroes

## Status

**READY**

## Description

add content-type text/yaml as supported content-type to import

## Related PRs
https://github.com/anymaniax/orval/discussions/108

branch | PR
------ | ------
other_pr_production | [link]()
other_pr_master | [link]()

## Todos
- [x] Tests
- [x] Documentation
- [x] Changelog Entry (unreleased)

2021-01-15 16:35 UTC, anymaniax requested changes

2021-01-15 16:35 UTC, anymaniax commented on src/core/importers/specs.ts
> +          if (isContentTypeTextPlain && typeof data === 'string') {
you need to do that for isContentTypeJson and isContentTypeYaml too. Just assign the format directly (format = 'json' for isContentTypeJson).

2021-02-09 14:17 UTC, wouterkroes commented
@anymaniax any thoughts on my comment regarding your requested code change?

2021-02-09 21:02 UTC, anymaniax commented
@wouterkroes which comment? There is only my request to assign the format linked to the content-type right?

2021-02-10 07:55 UTC, wouterkroes commented
Ah yes, and I replied to your code change request:
![image](https://user-images.githubusercontent.com/6161307/107480874-97fdaa80-6b7d-11eb-8f3f-fdcf94cd828e.png)

2021-02-10 13:20 UTC, anymaniax commented
You comment is in pending that why I don’t see it I think. I ask you to do that for the case where in the path you only have /specification without an extension. In that case you still correctly set the good format and avoid a possible error.

2021-02-10 14:04 UTC, wouterkroes commented
Updated! Hopefully, this is the desired implementation for the case you mentioned

2021-02-10 15:10 UTC, anymaniax approved these changes
Thanks for this new feature 🎉🚀

2021-02-10 15:10 UTC, merged