chore: mock generator builer type to strict
anymaniax/orval pull request #1356
Opened 2024-05-04 02:50 UTC by soartec-lab

## Status

**READY/WIP/HOLD**

## Description

`ClientMockBuilder` is old and not working, so i fixed it. And i sepalated types.

## Related PRs

none

## Todos

- [x] Tests
- [x] Documentation
- [x] Changelog Entry (unreleased)

## Steps to Test or Reproduce

That all tests pass

2024-05-04 12:04 UTC, melloware requested changes
Unit tests failing?

2024-05-05 01:14 UTC, soartec-lab commented
@melloware 
Thank you let me know.
Due to stricter `type` definitions, `@ts-expect-error` is no longer needed. The reason the test was failing was because it was generating a warning due to the unnecessary use of `@ts-expect-error`. I removed it.
So, could you review again ?

2024-05-05 10:49 UTC, melloware approved these changes

2024-05-06 01:34 UTC, soartec-lab commented
thanks. I merged it.

2024-05-06 01:34 UTC, merged