fix: allParamsOptional implemented in params and props
anymaniax/orval pull request #1361
Opened 2024-05-08 07:58 UTC by wouterkroes

## Status

Ready

## Description

- Enhanced the current build setting allParamsOptional (refer to https://github.com/anymaniax/orval/issues/1322).
- Fixed/removed the TODO comment (`Maybe ensure that 'paramType' isn't already undefined or null`). In my view, optional signifies a property marked with a ?, rather than extending the type with `| undefined | null`.

I experimented with these adjustments locally in a playground project with Orval clients: default (axios), vue-query, and angular.

## Related PRs

n/a

## Todos

n/a

## Steps to Test or Reproduce

n/a

2024-05-08 11:35 UTC, melloware approved these changes

2024-05-08 11:36 UTC, melloware commented
@Maxim-Mazurok you were recently in there as well want to give these a review?

2024-05-08 13:55 UTC, Maxim-Mazurok requested changes
This flag was working as intended, consider updating docs and/or creating a new config flag. See https://github.com/anymaniax/orval/issues/1322#issuecomment-2100634682

2024-06-03 23:35 UTC, soartec-lab commented
@wouterkroes 
I agree with they. I think this change is a workaround and essentially requires revising the definition of `OpenAPI` itself for the relevant use case. What do you think?

2024-06-04 07:15 UTC, wouterkroes commented
First of all, thanks to everyone for the responses.

This entire discussion has made me rethink what I wanted to achieve and the implementation I had in mind. As a result, I've changed my plan and no longer need the changes proposed in my pull request. Therefore, I suggest we close this pull request.

It would be beneficial if we could enhance the Orval documentation. @Maxim-Mazurok suggestion to "fix this issue by renaming allParamsOptional to allPathParamsOptional and/or updating the documentation" makes sense.

2024-06-04 23:46 UTC, soartec-lab commented
@wouterkroes 

I got it. Thanks to you for suggesting this, I found a way to improve it with another approach, so I appreciate it.
I'd prefer documenting the options instead of destructively renaming them, as it's a minor improvement, but would you update the documentation in a separate PR?

2024-06-13 00:08 UTC, soartec-lab commented
I updated docs at #1453

2024-06-13 00:47 UTC, closed without merging