fix(query): enabled reactivity fix
anymaniax/orval pull request #944
Opened 2023-09-21 01:29 UTC by BenGane

## Status

**READY/WIP**

## Description

Addresses the issue outlined in https://github.com/anymaniax/orval/issues/943

2023-09-25 05:08 UTC, Maxim-Mazurok approved these changes
Teammate here, this fix has been working well for us 👍

2023-09-28 03:04 UTC, anymaniax commented
Thanks for this @BenGane. There is a difference with #931?

2023-09-28 03:25 UTC, Maxim-Mazurok commented
> Thanks for this @BenGane. There is a difference with #931?

Yes, this one is making query `enabled` reactive, and #931 is making query parameters reactive. Not the same thing, and we use both patches currently.

I also wanted to give a little update that I've created a workitem for myself at work to go over all the issues PRs and make sure they are in a good shape so we can get them merged and get rid of patches that we use internally. It's in our quick&important project so it's likely I'll get to this pretty soon. Cheers!

2023-09-28 03:33 UTC, anymaniax commented
oki thanks @Maxim-Mazurok!

2023-09-28 03:34 UTC, anymaniax approved these changes
Thanks @BenGane!

2023-10-05 12:09 UTC, WickyNilliams commented on samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
> +    enabled: computed(() => !!unref(version && petId)),
is this correct? don't you want:

```ts
!!(unref(version) && unref(petId))
```

2023-10-09 01:39 UTC, Maxim-Mazurok requested changes

2023-10-09 01:39 UTC, Maxim-Mazurok commented on samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
> +    enabled: computed(() => !!unref(version && petId)),
Yes, great catch!

Verified like so:
```js
const x = computed(() => undefined);
const y = computed(() => 2);
const z1 = unref(x && y); // 2 <- unexpected
const z2 = unref(x) && unref(y); // undefined <- expected
```

2023-10-19 08:42 UTC, anymaniax commented on samples/vue-query/src/api/endpoints/petstoreFromFileSpecWithTransformer.ts
> +    enabled: computed(() => !!unref(version && petId)),
Is it ready to merged?

2023-11-03 12:18 UTC, melloware commented
Looks like conflicts need to be resolved...

2023-11-16 12:10 UTC, melloware commented
@BenGane @Maxim-Mazurok where are we with this PR?

2023-11-16 12:16 UTC, Maxim-Mazurok commented
Hello, as I've mentioned in other issues I've been busy with other work, however the Orval PRs are next on my list, I'd expect to see some progress next week. Cheers!

2023-11-29 02:35 UTC, closed without merging