fix: zod additional properties
anymaniax/orval pull request #972
Opened 2023-10-19 11:53 UTC by CxGarcia

## Status

**WIP** (pending tests)

## Description

- zod `additionalProperties` are parsed as either an `array` or `boolean` (ref to [code](https://github.com/anymaniax/orval/blob/8f1682ce72d721d8992b4c613513191b31029c7c/packages/zod/src/index.ts#L164). however, `parseProperty` function is treating them all as arrays and using array methods which causes errors
- if `additionalProperties` is to `true` then `passthrough` method is used so unknown keys aren't stripped from the object

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

```bash
git pull https://github.com/CxGarcia/orval
git checkout fix/zod-additional-properties
# run test pending
```

2023-10-19 13:20 UTC, melloware requested changes

2023-10-19 13:20 UTC, melloware commented on tests/specifications/additional-properties.yaml
> +  title: Addtional properties
```suggestion
  title: Additional properties
```

2023-10-19 13:25 UTC, melloware submitted a review, later dismissed

2023-10-26 13:10 UTC, melloware commented
Looks like tests are failing?

2023-11-03 12:17 UTC, melloware requested changes
Tests are still failing...

2023-11-15 21:06 UTC, melloware commented
Errors...

```
Error: generated/zod/additionalProperties.ts(18,16): error TS2554: Expected 1-3 arguments, but got 0.
Error: generated/zod/additionalProperties.ts(18,25): error TS2339: Property 'passthrough' does not exist on type 'ZodRecord<ZodString, ZodTypeAny>'.
```

2024-06-09 23:49 UTC, soartec-lab commented
Hi, @CxGarcia 
Since our PR was stagnant, created a new PR. You are welcome to participate in this discussion, so please comment here if you have any questions.

https://github.com/anymaniax/orval/pull/1443

If we do not hear from you, we will close this PR and move on to the new one.

2024-06-11 11:33 UTC, closed without merging

2024-06-11 11:33 UTC, melloware commented
@soartec-lab i am closing this one.  The new PR is the correct solution.